### ISSUE TITLE
Weather Icons from SimpleWeather

### ISSUE THREAD

**Issue by b3ck** [BrookeDot/SimplerWeather#2]
Been trying to get the icons from the original SimpleWeather to work with this but for the life of me I can't figure it out.  Any ideas? Kind Regards -b3ck

**Comment by folixg** [comment]
You will need to write a function that translates the [Dark Sky icon text](https://darksky.net/dev/docs#data-point) to a [Yahoo condition code](https://developer.yahoo.com/weather/documentation.html#codes). For example the input `'snow'`should return `16`. Then you can fetch the icons from Yahoo with the links that were used in [SimpleWeather](https://github.com/monkeecreate/jquery.simpleWeather/blob/master/jquery.simpleWeather.js#L86) and the Yahoo condition code.

**Comment by b3ck** [comment]
Awesome, thanks! @folixg 😃

**Comment by joasag** [comment]
@b3ck Can you supply this function? Looking for the same thing.

Thanks!

**Comment by jamesgillispie** [comment]
@b3ck wondering if you could provide an example of function. Much obliged

**Comment by Kipperlenny** [comment]
```javascript
var image = 'image404';
var html = '';
						switch(weather.icon) {
							case "snow": image = 16; break;
							case "clear-day": image = 32; break;
							case "clear-night": image = 31; break;
							case "rain": image = 12; break;
							case "snow": image = 16; break;
							case "sleet": image = 18; break;
							case "wind": image = 24; break;
							case "fog": image = 20; break;
							case "cloudy": image = 26; break;
							case "partly-cloudy-day": image = 30; break;
							case "partly-cloudy-night": image = 29; break;
							case "hail": image = 17; break;
							case "thunderstorm": image = 4; break;
							case "tornado": image = 0; break;
						}
html += '<img src="https://s.yimg.com/zz/combo?a/i/us/nws/weather/gr/'+image+'ds.png">';
```
